# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y95Rvm1T8-a0s2b3SZ9A7fgmwFEDUbUF
"""

import seaborn as sns
iris = sns.load_dataset("iris")

virginica = iris[iris['species'] == 'virginica']
minimum_values = virginica.min()

print(minimum_values)

mean_pl = iris['petal_length'].mean()
filtered_df = iris[iris['petal_length'] > mean_pl]
print(len(filtered_df))

titanic = sns.load_dataset("titanic")
count = len(titanic[(titanic['pclass'] == 2) & (titanic['survived'] == 1)])
print(count)
subset = titanic[(titanic['pclass'] == 1) & (titanic['survived'] == 0)]
print(subset['age'].min(), subset['age'].max())
females = titanic[titanic['sex'] == 'female']
percent = (females['survived'].mean() * 100)
print(round(percent))

titanic.isnull().sum()